### PR TITLE
Updated Insights and Graph Modules (Read Comments)

### PR DESCRIPTION
**Pull request by cstohlmann**
Graph and Insights modules assets are finalized for module v0.1rc1 and ready for review. Documentation and assets have been updated accordingly.

### CODE REVIEW

**Comment by cstohlmann** [comment]
Graph module is now ready for release. Whoever accepts the pull request, could you:

-  name the release "module_graph_v0.1rc1" 
- tag the release with a new tag "module_graph_v0.1rc1"
- Enter the description: 
   * "The initial release of the Microsoft Graph module which is used to land, ingest, correct schemas, and refine data from MS Graph into the data lake stored in ADLS."
- And, attach the zip file to the release (attached with this comment).

This can be released as a pre-release, since the module production migration guidance is not finished (and the tutorial/video is to be updated). Thanks!
[module_graph_v0.1rc1.zip](https://github.com/microsoft/OpenEduAnalytics/files/10406303/module_graph_v0.1rc1.zip)

**Comment by cstohlmann** [comment]
Insights module is now ready for release. Whoever accepts the pull request, could you:

-  name the release "module_insights_v0.1rc1" 
- tag the release with a new tag "module_insights_v0.1rc1"
- Enter the description: 
   * "The initial release of the Microsoft Education Insights module which is used to land, ingest, correct schemas, and refine data from SDS/MS Education Insights into the data lake stored in ADLS."
- And, attach the zip file to the release (attached with this comment).

This can be released as a pre-release, since the module may have some bugs with refining some PersonDemographic tables (and the tutorial/video is to be added). Thanks!
[module_insights_v0.1rc1.zip](https://github.com/microsoft/OpenEduAnalytics/files/10428725/module_insights_v0.1rc1.zip)

**Comment by cstohlmann** [comment]
For the assets to properly run - the OEA_py notebook will need to be updated so that the refine function doesn't assume every primary key is pseudonymized.

**Comment by cstohlmann** [comment]
Added the latest Learning Analytics Package assets, that leans on v0.7 of the OEA framework. Notebook and Pipeline READMEs were also updated accordingly. Expected to push one more set of finalized Learning Analytics assets for v1.0 of the package.

**Review by genegc — APPROVED** [review]

**Pull request merged**
